export const AUTHENTICATE_REQ = 'AUTHENTICATE_REQ';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE';

export const GET_BOARDS_REQ = 'GET_BOARDS_REQ';
export const GET_BOARDS_SUCCESS = 'GET_BOARDS_SUCCESS';
export const GET_BOARDS_FAILURE = 'GET_BOARDS_FAILURE';

export const GET_BOARD_SOUNDS_REQ = 'GET_BOARD_SOUNDS_REQ';
export const GET_BOARD_SOUNDS_SUCCESS = 'GET_BOARD_SOUNDS_SUCCESS';
export const GET_BOARD_SOUNDS_FAILURE = 'GET_BOARD_SOUNDS_FAILURE';

export const GET_KEYS_REQ = 'GET_KEYS_REQ';
export const GET_KEYS_SUCCESS = 'GET_KEYS_SUCCESS';
export const GET_KEYS_FAILURE = 'GET_KEYS_FAILURE';

export const GET_SHORTCUT_COMMANDS_REQ = 'GET_SHORTCUT_COMMANDS_REQ';
export const GET_SHORTCUT_COMMANDS_SUCCESS = 'GET_SHORTCUT_COMMANDS_SUCCESS';
export const GET_SHORTCUT_COMMANDS_FAILURE = 'GET_SHORTCUT_COMMANDS_FAILURE';

export const PLAY_SOUND = 'PLAY_SOUND';
export const KILL_ALL_SOUNDS = 'KILL_ALL_SOUNDS';
export const KEY_PRESS = 'KEY_PRESS';

export const ASSIGN_SHORTCUT_KEYS = 'ASSIGN_SHORTCUT_KEYS';

export const INIT = '@@INIT';
